### ISSUE TITLE
Big problem

### ISSUE THREAD

**Issue by nbqofficial** [TusKabina/Game-Pong#1]
The only issue I have is that this is not listed on Steam.

**Comment by TusKabina** [comment]
Hello official Nbq. Thank you for your comment! Unfortunately currently I do not have plans to release this game on Steam.
Thank you for your support!

**Comment by nbqofficial** [comment]
> Hello official Nbq. Thank you for your comment! Unfortunately currently I do not have plans to release this game on Steam.
> 
> Thank you for your support!

I think this game might be a good release on Steam. You should consider it even though the graphics are ultra high and you would need an insane processing power to run it.
